#!/usr/bin/env python

import pycoreutils, sys
from os.path import basename

p = pycoreutils.optparse()
(opts, args) = p.parse_args()

if len(args) == 0:
    print u"basename: missing operand"
    print u"Try `basename --help' for more information."
    sys.exit(1)

if len(args) > 2:
    print u"basename: extra operand `%s'" % (args[2])
    print u"Try `basename --help' for more information."
    sys.exit(1)

b = basename(args[0])

if len(args) == 2:
    b = b.rstrip(args[1])

print b
