#!/usr/bin/env python

import pycoreutils, sys
from os.path import dirname

p = pycoreutils.optparse()
(opts, args) = p.parse_args()

if len(args) == 0:
    print u"dirname: missing operand"
    print u"Try `dirname --help' for more information."
    sys.exit(1)

if len(args) > 1:
    print u"dirname: extra operand `%s'" % (args[1])
    print u"Try `dirname --help' for more information."
    sys.exit(1)

d = dirname(args[0].rstrip('/'))

if d == '':
    d = '.'

print d
