#!/usr/bin/env python

import os, pycoreutils, sys

p = pycoreutils.optparse()
p.set_defaults(mode=0777)
p.add_option("-p", "--parents", action="store_true", dest="recursive",
        help="no error if existing, make parent directories as needed")
p.add_option("-m", "--mode=MODE", action="store", dest="mode",
        help="set file mode (as in chmod), not a=rwx - umask")
(opts, args) = p.parse_args()

if len(args) < 1:
    print "mkdir: missing operand"
    print "Try `mkdir --help' for more information."
    sys.exit(1)

for arg in args:
    if opts.recursive:
        os.makedirs(arg, opts.mode)
    else:
        try:
            os.mkdir(arg, opts.mode)
        except OSError:
            print "mkdir: cannot create directory '%s': No such file or directory" % (arg)