#!/usr/bin/env python

import pycoreutils, shutil, sys

p = pycoreutils.optparse()
p.add_option("-v", "--verbose", action="store_true", dest="verbose",
        help="print the kernel name")
(opts, args) = p.parse_args()

if len(args) == 0:
    print u"mv: missing file operand"
    print u"Try 'mv --help' for more information."
    sys.exit(1)
if len(args) == 1:
    print u"mv: missing destination file operand after '%s'" % (args[0])
    print u"Try 'mv --help' for more information."
    sys.exit(1)

dest = args.pop()

for src in args:
    if opts.verbose:
        print u"'%s' -> '%s'" % (src, dest)
    try:
        shutil.move(src, dest)
    except IOError, err:
        print u"mv: %s" % (err.strerror)
        sys.exit(1)
