#!/usr/bin/env python

import pycoreutils
from os import getcwdu, getenv
from os.path import realpath

p = pycoreutils.optparse()
p.add_option("-L", "--logical", action="store_true", dest="logical",
        help="use PWD from environment, even if it contains symlinks")
p.add_option("-P", "--physical", action="store_true", dest="physical",
        help="avoid all symlinks")
(opts, args) = p.parse_args()

if opts.logical:
    print getenv('PWD')
elif opts.physical:
    print realpath(getcwdu())
else:
    print getcwdu()