#!/usr/bin/env python

import pycoreutils, os, random, sys

# TODO: This program acts as 'shred -x', and doesn't round file sizes up to the next full block

p = pycoreutils.optparse()
p.add_option("-n", "--iterations", action="store", dest="iterations", default=3,
        help="overwrite ITERATIONS times instead of the default (3)")
p.add_option("-v", "--verbose", action="store_true", dest="verbose",
        help="show progress")
(opts, args) = p.parse_args()

if len(args) == 0:
    print u"mv: missing file operand"
    print u"Try 'shred --help' for more information."
    sys.exit(1)

for arg in args:
    for i in xrange(opts.iterations):
        size = os.stat(arg).st_size
        fd = pycoreutils.fopen(arg, mode='w')
        print 'Size:', size
        fd.seek(0)
        for i in xrange(size):
            # Get random byte
            b = "".join(chr(random.randrange(0,256)))
            fd.write(b)
        fd.close()
