#!/usr/bin/env python

import pycoreutils, time

p = pycoreutils.optparse()
(opts, args) = p.parse_args()

interval = 1.0
f = open('/var/log/messages')

while 1:
    where = f.tell()
    line = f.readline()
    if not line:
        time.sleep(interval)
        f.seek(where)
    else:
        print line,
