#!/usr/bin/env python

import pycoreutils, os, sys, time

# TODO: Implement --date, --time and -t

p = pycoreutils.optparse()
p.add_option("-a", action="store_true", dest="accessonly",
        help="change only the access time")
p.add_option("-c", "--no-create", action="store_true", dest="nocreate",
        help="do not create any files")
p.add_option("-f", action="store_true", dest="thisoptionshouldbeignored",
        help="(ignored)")
p.add_option("-m", action="store_true", dest="modonly",
        help="change only the modification time")
p.add_option("-r", "--reference", action="store", dest="reference",
        help="use this file's times instead of current time")
(opts, args) = p.parse_args()

if len(args) == 0:
    print u"touch: missing operand"
    print u"Try 'touch --help' for more information."
    sys.exit(1)

atime = mtime = time.time()

for arg in args:
    if not os.path.exists(arg):
        if opts.nocreate:
            # Skip file
            break
        else:
            # Create empty file
            open(arg, 'w').close()
            

    if opts.reference:
        atime = os.path.getatime(opts.reference)
        mtime = os.path.getmtime(opts.reference)
    if opts.accessonly:
        mtime = os.path.getmtime(arg)
    if opts.modonly:
        atime = os.path.getatime(arg)
    os.utime(arg, (atime, mtime))

