#!/usr/bin/env python

import pycoreutils, sys

(opts, args) = pycoreutils.optparse().parse_args()

x = ''
for arg in args:
    x += arg + ' '
x = x.strip()

if x == '':
    x = 'y'

try:
    while 1:
        print x
except KeyboardInterrupt:
    sys.exit()